services:
  statistic-server:
    build: ./staticstic-service/statistic-server
    image: statistic-server
    container_name: statistic-server
    ports:
      - "9090:9090"
    depends_on:
      - statistic-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistic-db:5432/statistic
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  statistic-db:
    image: postgres:16.1
    container_name: statistic-db
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "6541:5432"

#  ewm-service:
#    ports:
#      - "8080:8080"
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=user
#      - POSTGRES_DB=statistic
#
#  ewm-db:
#    image: postgres:16.1
